name: ${name}
main: io.github.secretdataz.StrictWGUseFlag.StrictWGUseFlag
version: ${version}-${maven.build.timestamp}
description: Makes WorldGuard's USE flag more strict.
author: iSuzutsuki
depend: [WorldGuard]